// Generated by sqltyper 1.0.1 from arrayTypes.sql.
// Do not edit directly. Instead, edit arrayTypes.sql and re-run sqltyper.

import * as postgres from '../postgres'

export async function arrayTypes(
  sql: postgres.Sql<{}>
): Promise<Array<{ oid: number; typelem: number }>> {
  const result = await sql.unsafe(`SELECT oid, typelem
FROM pg_catalog.pg_type
WHERE typlen = -1 AND typelem != 0 AND typarray = 0
`)
  return result
}
